# Generated by Django 5.2.8 on 2025-11-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otp_is_used_alter_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
